sudo: false
language: php
php:
    - 7
    - 7.1
matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1
services: sqlite3
before_script:
    - composer self-update
    - composer install --prefer-source
script:
    - chmod -R 777 tests/build
    - ./vendor/bin/phpunit --coverage-clover=tests/build/clover.xml
    - ./vendor/bin/phpcpd src/
    - ./vendor/bin/phploc src/
    - chmod 777 tests/build/clover.xml
after_success:
    - travis_retry php ./vendor/bin/coveralls -v
